language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.3

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - gh-pages
    - /pages-(.*)/

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

notifications:
  email: true
