language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - develop

before_install:
  - npm install hexo-cli -g
  - npm install hexo --save

before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'bot@travis-ci.org'
  - sed -i'' "s~git@github.com:zghurskyi/zghurskyi.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/zghurskyi/zghurskyi.github.io.git~" _config.yml

script:
  - hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: develop
