title:             Oxymorus Blog
email:             oleksii.zghurskyi@gmail.com
description:       Yet Another Notes On Programming
author:            Oleksii Zghurskyi
baseurl:           "/"
url:               "https://www.oxymorus.com/"

# Social Profiles
twitter_username:  zghurskyi
github_username:   zghurskyi
facebook_username: oleksii.zghurskyi

# Build settings
highlighter:       rouge
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
